version: '3'

services:
  app:
    image: cthulhoo/ttrss-fpm-pgsql-static:${BUILD_TAG}
    build: 
      context:
        ./app
    restart: unless-stopped

  web-nginx:
    image: cthulhoo/ttrss-web-nginx:latest
    build: ./web-nginx
    restart: unless-stopped
    depends_on:
      - app

