version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: cthulhoo/ttrss-fpm-pgsql-static:${BUILD_TAG}
    build: 
      context:
        ./app
    restart: unless-stopped
    volumes:
      - app:/var/www/html
    depends_on:
      - db

#  web:
#    image: cthulhoo/ttrss-web:latest
#    build: ./web
#    restart: unless-stopped
#    ports:
#      - ${HTTP_PORT}:2015
#    volumes:
#      - app:/var/www/html:ro
#    depends_on:
#      - app

#  web-ssl:
#    image: cthulhoo/ttrss-web-ssl:latest
#    build: ./web-ssl
#    restart: unless-stopped
#    environment:
#      - CADDYPATH=/certs
#      - HTTP_HOST=${HTTP_HOST}
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - app:/var/www/html:ro
#      - certs:/certs
#    depends_on:
#      - app

  web-nginx:
    image: cthulhoo/ttrss-web-nginx:latest
    build: ./web-nginx
    restart: unless-stopped
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app

volumes:
  db:
  app:  
  certs:
  backups:
