version: '3'

# set database password in .env
# please don't use quote (') or (") symbols in variables

services:
  db:
    image: cthulhoo/ttrss-db-pgsql-count-bits:${BUILD_TAG}
    build:
      context:
        ./db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:    
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

volumes:
  db:

